name: Build and Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install FFmpeg and Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg libwebp-dev libopus-dev libavformat-dev
        
    - name: Install npm dependencies
      run: |
        npm install
        
    - name: Start application
      run: |
        npm start
